### PR TITLE
Refactor module for use with bedrock@2.

### PR DESCRIPTION
**Pull request by mattcollier**

### CODE REVIEW

**Comment by dlongley** [comment]
Is there a reason why we're still supporting this module? It should be deprecated.

**Review by dlongley — APPROVED** [review]
Approving in case we really need this somewhere ... but I'd like us to stop supporting this module.

**Comment by mattcollier** [comment]
This is main reason why this still lingers: https://github.com/digitalbazaar/bedrock-account/blob/master/package.json#L33

**Comment by dlongley** [comment]
I see. We should look into removing it from bedrock-account (https://github.com/digitalbazaar/bedrock-account/issues/11).

**Pull request merged**
